# Generated by Django 5.2.7 on 2025-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Service 1', 'Service 1'), ('Service 2', 'Service 2'), ('Service 3', 'Service 3')], max_length=50)),
                ('doctor', models.CharField(choices=[('Doctor 1', 'Doctor 1'), ('Doctor 2', 'Doctor 2'), ('Doctor 3', 'Doctor 3')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
