# Generated by Django 5.2.7 on 2025-10-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
