# Generated by Django 5.2.7 on 2026-08-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_seed_dentists'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='main_appoin_appoint_3054b0_idx',
            old_name='main_appoi_appoin_1a2b3c_idx',
        ),
    ]
